name: Spot in

networks:
  spotin_network:
    name: spotin_network

services:
  spotin:
    container_name: spotin
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mailpit:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - spotin_network
    env_file:
      - .env
    environment:
      - SPOT_IN_DATABASE_URL=postgresql://${SPOT_IN_DATABASE_USER}:${SPOT_IN_DATABASE_PASSWORD}@postgres:5432/${SPOT_IN_DATABASE_NAME}
      - SPOT_IN_MAIL_HOST=mailpit
    ports:
      - 3000:3000

  mailpit:
    container_name: spotin-mailpit
    image: axllent/mailpit:v1.18
    networks:
      - spotin_network
    ports:
      - 1025:1025
      - 8025:8025

  postgres:
    container_name: spotin-postgres
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=spotin
      - POSTGRES_USER=spotin
      - POSTGRES_PASSWORD=spotin
    networks:
      - spotin_network
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
