services:
  spotin:
    container_name: spotin
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mailhog:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000

  mailhog:
    container_name: spotin-mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025

  postgres:
    container_name: spotin-postgres
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=spotin
      - POSTGRES_USER=spotin
      - POSTGRES_PASSWORD=spotin
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 3
