export const BASE_URL = 'SPOT_IN_BASE_URL';
export const JWT_ISSUER = 'SPOT_IN_JWT_ISSUER';
export const JWT_AUDIENCE = 'SPOT_IN_JWT_AUDIENCE';
export const JWT_ACCESS_TOKEN_SECRET = 'SPOT_IN_JWT_ACCESS_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME =
	'SPOT_IN_JWT_ACCESS_TOKEN_EXPIRATION_TIME';
export const JWT_ACCESS_TOKEN_COOKIE_NAME =
	'SPOT_IN_JWT_ACCESS_TOKEN_COOKIE_NAME';
export const JWT_REFRESH_TOKEN_SECRET = 'SPOT_IN_JWT_REFRESH_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME =
	'SPOT_IN_JWT_REFRESH_TOKEN_EXPIRATION_TIME';
export const JWT_REFRESH_TOKEN_COOKIE_NAME =
	'SPOT_IN_JWT_REFRESH_TOKEN_COOKIE_NAME';
export const MAIL_HOST = 'SPOT_IN_MAIL_HOST';
export const MAIL_PORT = 'SPOT_IN_MAIL_PORT';
export const MAIL_USER = 'SPOT_IN_MAIL_USER';
export const MAIL_PASS = 'SPOT_IN_MAIL_PASS';
export const MAIL_SECURE = 'SPOT_IN_MAIL_SECURE';
export const MAIL_SENDER_NAME = 'SPOT_IN_MAIL_SENDER_NAME';
export const NODE_ENV = 'NODE_ENV';

export interface EnvironmentVariables {
	[BASE_URL]: string;
	[JWT_ISSUER]: string;
	[JWT_AUDIENCE]: string;
	[JWT_ACCESS_TOKEN_SECRET]: string;
	[JWT_ACCESS_TOKEN_EXPIRATION_TIME]: string;
	[JWT_ACCESS_TOKEN_COOKIE_NAME]: string;
	[JWT_REFRESH_TOKEN_SECRET]: string;
	[JWT_REFRESH_TOKEN_EXPIRATION_TIME]: string;
	[JWT_REFRESH_TOKEN_COOKIE_NAME]: string;
	[MAIL_HOST]: string;
	[MAIL_PORT]: string;
	[MAIL_USER]: string;
	[MAIL_PASS]: string;
	[MAIL_SECURE]: boolean;
	[MAIL_SENDER_NAME]: string;
	[NODE_ENV]: string;
}
