name: Build and push Docker image to GitHub
run-name: Build and push Docker image to GitHub
on:
  push:
    paths:
      - '.github/workflows/build-and-push-docker-image-to-github.yml'
      - 'prisma/**'
      - 'public/**'
      - 'src/**'
      - 'views/**'
      - '.env.defaults'
      - 'Dockerfile'
      - 'nest-cli.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.build.json'
      - 'tsconfig.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        uses: ./.github/actions
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-engine
          docker-image-context: .
    outputs:
      docker-image-tags: ${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }}
